---
title: "RealChangeAnalysis"
author: "Camille Zaug"
date: "5/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(klaR)
```


```{r}
data <- read.csv("realchange1.csv")
```

```{r}
head(data)
```


## Including Plots

You can also embed plots, for example:

```{r}

data1 <- data[,-c(34:43)]

head(data1)
```

```{r}
summary(data1)
```


```{r}


  #data2 <- data1 %>% mutate(Living.Stable = ifelse(biopsy$class == "malignant",1,0))

data1$Living[data1$Living=="Staying with friends/family"] <- 2
data1$Living[data1$Living=="I have a place"] <- 3
data1$Living[data1$Living=="Transitional Housing"] <- 2


summary(data1)
```




```{r}
fit <- lm(Post.hours~Living+I(Living^2),data = data1)
```


```{r}
summary(fit)
```


```{r}
boxplot(data1$Post.hours~data1$Living, ylab = "Hours spent at post", xlab = "Living situation (least to most stable)")
```


```{r}
plot(jitter(data1$Living,.2),jitter(data1$Post.hours),pch=20,xlab ="Living situation stability (least to most stable)", ylab = "Hours spent at post", xaxp  = c(1, 3, 2))
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
